import React, { useMemo, useState } from 'react';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';
import { ArrowLeft, Search, BookOpen } from 'lucide-react';

// ── Glossary entries ──────────────────────────────────────────────────────────
const GLOSSARY = [
  // STOCHASTIC CALCULUS
  {
    cat: 'STOCHASTIC CALCULUS',
    term: "Itô's Lemma",
    notation: 'df = (∂f/∂t + μ·∂f/∂x + ½σ²·∂²f/∂x²) dt + σ·∂f/∂x dW',
    def: "The chain rule for stochastic processes. For a twice-differentiable function f(t, X_t) where X_t follows an Itô diffusion dX = μ dt + σ dW, Itô's Lemma produces a second-order correction (½σ²·∂²f/∂x²) that ordinary calculus lacks. This term — the 'Itô correction' — is the algebraic core behind the Black-Scholes PDE and virtually every option-pricing derivation.",
  },
  {
    cat: 'STOCHASTIC CALCULUS',
    term: 'Girsanov Theorem',
    notation: 'dQ/dP = exp(-½∫θ² ds - ∫θ dW)',
    def: 'Tells us how to change probability measure in a diffusion model. Given a measure P, Girsanov constructs an equivalent measure Q under which a drifted Brownian motion becomes driftless. In finance this is how one passes from the real-world (P) measure to the risk-neutral (Q) measure used for pricing.',
  },
  {
    cat: 'STOCHASTIC CALCULUS',
    term: 'Radon-Nikodym Derivative',
    notation: 'dQ/dP',
    def: 'The density that converts probabilities between two equivalent measures. If dQ/dP exists, expectations transform as E^Q[X] = E^P[X · dQ/dP]. Under Girsanov this density is an exponential martingale; in discrete finance it is the ratio of state-price probabilities.',
  },
  {
    cat: 'STOCHASTIC CALCULUS',
    term: 'Brownian Motion',
    notation: 'W_t ~ N(0, t), independent increments',
    def: 'The canonical continuous-time martingale. A stochastic process with stationary independent Gaussian increments, continuous paths, and W_0 = 0. Almost surely nowhere differentiable, with quadratic variation [W]_t = t. The workhorse driver of nearly every continuous-time finance model.',
  },
  {
    cat: 'STOCHASTIC CALCULUS',
    term: 'Stochastic Differential Equation (SDE)',
    notation: 'dX_t = μ(X,t) dt + σ(X,t) dW_t',
    def: 'An equation describing the infinitesimal evolution of a random process via a deterministic drift term and a diffusion term driven by Brownian motion. Numerical solutions via Euler-Maruyama, Milstein, or analytic solutions when available (e.g. GBM, OU, CIR). The language in which asset-price dynamics are written.',
  },
  {
    cat: 'STOCHASTIC CALCULUS',
    term: 'Risk-Neutral Measure',
    notation: 'Q: E^Q[S_T e^-rT] = S_0',
    def: 'The pricing measure under which all discounted tradable assets are martingales. Under Q the drift of every asset equals the risk-free rate (in the absence of dividends). Pricing derivatives reduces to taking risk-neutral expectations of discounted payoffs — the fundamental theorem of asset pricing.',
  },
  {
    cat: 'STOCHASTIC CALCULUS',
    term: 'Martingale',
    notation: 'E[X_t | F_s] = X_s for s ≤ t',
    def: "A process whose conditional expectation given the past equals its current value — mathematically, 'no drift.' Under the risk-neutral measure, discounted asset prices are martingales. The martingale representation theorem underlies hedging: any payoff can be replicated by trading the underlying if the filtration is generated by a Brownian motion.",
  },

  // DERIVATIVES
  {
    cat: 'DERIVATIVES',
    term: 'Black-Scholes Model',
    notation: 'C = S·N(d1) - K·e^-rT·N(d2)',
    def: "The 1973 closed-form formula for European option prices under constant volatility, constant rates, and geometric Brownian motion for the underlying. d1 = (ln(S/K) + (r + ½σ²)T) / (σ√T), d2 = d1 - σ√T. The model's assumptions are empirically false (vol is not constant, tails are fat) but it remains the universal language for quoting option prices via implied volatility.",
  },
  {
    cat: 'DERIVATIVES',
    term: 'Greeks (Δ, Γ, V, Θ, ρ)',
    notation: 'Δ = ∂C/∂S, Γ = ∂²C/∂S², V = ∂C/∂σ',
    def: 'Partial derivatives of option price with respect to market variables. Delta (Δ) = price sensitivity to underlying; Gamma (Γ) = rate of change of delta; Vega (V) = sensitivity to volatility; Theta (Θ) = time decay; Rho (ρ) = sensitivity to interest rate. Used for hedging and risk management — a delta-hedged position immunises against small moves in the underlying.',
  },
  {
    cat: 'DERIVATIVES',
    term: 'Implied Volatility',
    notation: 'σ_imp : C_mkt = BS(S, K, T, r, σ_imp)',
    def: "The volatility input that, when plugged into Black-Scholes, reproduces the market price of an option. Because BS is monotone in σ, this inverse is unique. Implied vols vary by strike (smile/skew) and maturity (term structure), forming the 'volatility surface' — a rich object that encodes the market's forward-looking distributional assumptions.",
  },
  {
    cat: 'DERIVATIVES',
    term: 'Put-Call Parity',
    notation: 'C - P = S - K·e^-rT',
    def: 'Model-free relation between European call and put prices with the same strike and maturity. Follows from a static replication argument: long call + short put + cash K·e^-rT = long underlying. Violations imply arbitrage. Used to check options data quality and imply dividend / borrow rates.',
  },
  {
    cat: 'DERIVATIVES',
    term: 'Vanna',
    notation: 'Vanna = ∂²C/∂S∂σ = ∂Δ/∂σ',
    def: 'Second-order Greek: sensitivity of delta to volatility (equivalently, sensitivity of vega to spot). Becomes material when the vol surface is skewed. Traders running large delta-hedged options books are intrinsically exposed to vanna through the skew — a sharp move in spot that coincides with a change in skew P&Ls them.',
  },
  {
    cat: 'DERIVATIVES',
    term: 'Volga',
    notation: 'Volga = ∂²C/∂σ² = ∂V/∂σ',
    def: "Second-order Greek: sensitivity of vega to volatility — the 'vega of vega.' Quantifies the curvature of an option's price in vol space. Out-of-the-money options have high volga; ATM options have near-zero volga. Essential for pricing volatility derivatives (variance swaps, VIX options) where vol-of-vol matters.",
  },
  {
    cat: 'DERIVATIVES',
    term: 'Local Volatility',
    notation: 'σ_loc(S,t) = √(2·(∂C/∂T + rK·∂C/∂K) / (K²·∂²C/∂K²))',
    def: "Dupire's (1994) deterministic volatility function σ(S, t) constructed to match the entire observed vol surface exactly. Under local vol, the asset follows dS = rS dt + σ_loc(S,t)S dW. Useful for path-dependent exotics but predicts unrealistic dynamics of the smile over time — flat forwards, shrinking skew.",
  },
  {
    cat: 'DERIVATIVES',
    term: 'Stochastic Volatility (Heston / SABR)',
    notation: 'dσ² = κ(θ - σ²) dt + ξσ dZ (Heston)',
    def: "Models where volatility itself is a stochastic process correlated with the asset. Heston's (1993) mean-reverting square-root variance gives semi-analytic option prices via Fourier transform. SABR (Hagan et al. 2002) is the industry standard for interest-rate options with a closed-form implied-vol approximation. Both produce realistic smile dynamics unlike local vol.",
  },

  // PORTFOLIO THEORY
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Sharpe Ratio',
    notation: 'SR = (E[R] - R_f) / σ(R)',
    def: "The standard risk-adjusted return metric. Excess return over the risk-free rate divided by the standard deviation of returns. Annualised by √252 for daily data. Treats upside and downside volatility symmetrically — a strategy with frequent small gains and rare large losses can hide poor risk profile behind a flattering Sharpe.",
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Sortino Ratio',
    notation: 'Sortino = (E[R] - R_f) / σ_down(R)',
    def: 'Sharpe ratio variant using only the downside deviation — standard deviation of negative returns — in the denominator. Better captures loss aversion by rewarding strategies that have volatile upside but contained downside. Requires an explicit MAR (minimum acceptable return), often zero or the risk-free rate.',
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Calmar Ratio',
    notation: 'Calmar = CAGR / |MaxDD|',
    def: 'Annualised return divided by the absolute maximum drawdown, usually computed over a 3-year rolling window. Favoured by CTAs and systematic macro funds where drawdown control is the primary risk metric. Highly sensitive to the worst single drawdown in the sample — a single crisis drives the score.',
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Maximum Drawdown',
    notation: 'MaxDD = max_t (max_{s≤t} V_s - V_t) / max_{s≤t} V_s',
    def: 'The largest peak-to-trough decline in portfolio value over the sample. A path-dependent statistic, unlike variance-based measures. Investors psychologically tolerate losses up to ~20–30% before redeeming; strategies must be sized so worst-case drawdown respects this constraint. Expected max drawdown scales with volatility × √horizon.',
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Information Ratio',
    notation: 'IR = α / σ(ε)',
    def: "Sharpe ratio of active returns relative to a benchmark. Alpha divided by tracking error (residual volatility after removing benchmark exposure). Measures a manager's skill per unit of active risk taken. A long-term IR above 0.5 is considered very good for an active equity manager; above 1.0 is exceptional.",
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Beta',
    notation: 'β = Cov(R, R_m) / Var(R_m)',
    def: "Slope from the OLS regression of an asset's excess returns on market excess returns. Measures systematic (non-diversifiable) risk exposure. A stock with β = 1.2 amplifies market moves by 20%. CAPM predicts expected excess return is proportional to beta; empirically the relation is weaker than theory and varies by regime.",
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Alpha',
    notation: 'α = E[R] - (R_f + β·(E[R_m] - R_f))',
    def: "The intercept from a factor-model regression — the portion of return not explained by exposures to systematic factors. Positive alpha represents manager skill (or model misspecification). In a well-specified factor world, alpha should be small and random; persistent alpha is rare and the basis of active management's fee justification.",
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Factor Model',
    notation: 'R_i = α_i + Σ β_ik · F_k + ε_i',
    def: 'Regression of asset returns on a set of systematic factors (market, size, value, momentum, quality, etc.). Fama-French 3- and 5-factor models are the academic standard. Used for return attribution, risk decomposition, portfolio construction, and hedging unwanted exposures. Factors may be statistical (PCA), fundamental (Barra), or macro (yields, commodities, FX).',
  },
  {
    cat: 'PORTFOLIO THEORY',
    term: 'Efficient Frontier',
    notation: 'w* = argmin w^T Σ w  s.t.  w^T μ = μ*',
    def: 'The set of portfolios offering maximum expected return for a given variance, derived by Markowitz (1952). Each point solves a mean-variance quadratic program. Empirically unstable — small changes in estimated mean returns produce wild shifts in optimal weights. Robust variants (Black-Litterman, shrinkage, hierarchical risk parity) address this.',
  },

  // MARKET MICROSTRUCTURE
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'Bid-Ask Spread',
    notation: 'Spread = P_ask - P_bid',
    def: "Difference between the lowest offer and the highest bid on the order book. Compensates market makers for adverse-selection risk, inventory risk, and order-processing costs. Decomposes into these three components via Stoll, Huang-Stoll, or Glosten-Harris models. A key transaction cost and a proxy for liquidity.",
  },
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'Market Impact',
    notation: 'Δp ~ λ · Q^β',
    def: 'The price movement caused by trading. Almgren-Chriss decompose it into temporary impact (reverses after the trade) and permanent impact (information component that persists). Empirically, impact scales as roughly the square-root of participation (β ≈ 0.5). A dominant cost for institutional execution.',
  },
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'Order Book',
    notation: 'L2: {(price, size)} bid + ask queues',
    def: 'The data structure aggregating all resting limit orders on a venue. Level 1 = best bid/ask + sizes; Level 2 = depth at each price level; Level 3 = individual order identifiers. Orders are matched by price-time priority in most equity markets. Reconstructing the book from trade/quote feeds is the foundation of HFT research.',
  },
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'VWAP (Volume-Weighted Average Price)',
    notation: 'VWAP = Σ(p_i · v_i) / Σv_i',
    def: 'The average price over a period weighted by traded volume. A common execution benchmark — institutional orders are often sliced to track intraday VWAP, since this is the average price at which the market transacted. Beats TWAP in high-volume regimes; underperforms when volume profile is misforecasted.',
  },
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'TWAP (Time-Weighted Average Price)',
    notation: 'TWAP = (1/T) · ∫_0^T p_t dt',
    def: 'Average price sampled at equal time intervals, ignoring volume. Simpler execution benchmark, widely used for less liquid names where volume prediction is unreliable. A TWAP algorithm releases equal-sized child orders on a fixed schedule — predictable, which is both a strength (transparent) and weakness (gameable).',
  },
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'Adverse Selection',
    notation: 'E[v | trade at ask] > midprice',
    def: 'The cost market makers pay when informed traders pick off their stale quotes. A counterparty that buys from you is more likely to know the asset is worth more than your ask — on average your quotes lose money to informed flow. Market makers widen spreads or flicker quotes to mitigate. Central to Glosten-Milgrom and Kyle models.',
  },
  {
    cat: 'MARKET MICROSTRUCTURE',
    term: 'Amihud Illiquidity',
    notation: 'ILLIQ = (1/D) · Σ |r_t| / V_t',
    def: "Amihud's (2002) illiquidity measure: the average ratio of absolute daily return to dollar volume. Captures price impact per dollar traded — high values indicate that small volumes move prices significantly. Useful across panels where bid-ask or tick data is unavailable. Illiquid stocks command higher expected returns (Amihud liquidity premium).",
  },

  // FIXED INCOME
  {
    cat: 'FIXED INCOME',
    term: 'Duration',
    notation: 'D_mod = -(1/P) · ∂P/∂y',
    def: "First-order measure of a bond's price sensitivity to yield changes. Modified duration is the percentage price change per 1% yield shift. Macaulay duration is the weighted average time to cash flows. A 10Y Treasury has duration ~9, meaning a 100bp yield move changes its price by ~9%. The fundamental interest-rate risk metric.",
  },
  {
    cat: 'FIXED INCOME',
    term: 'Convexity',
    notation: 'C = (1/P) · ∂²P/∂y²',
    def: "Second-order correction to duration. The true price-yield relation is convex — durations alone underestimate price for large yield moves in either direction. Convexity is always positive for option-free bonds (good for holders), negative for MBS or callable bonds where the issuer's option reduces upside. ΔP/P ≈ -D·Δy + ½·C·Δy².",
  },
  {
    cat: 'FIXED INCOME',
    term: 'DV01 (Dollar Value of an 01)',
    notation: 'DV01 = -∂P/∂y · 0.0001',
    def: 'Dollar change in price for a 1 basis-point change in yield. A portfolio-level risk metric widely used on rates desks — positions are sized in DV01 to equalise risk across instruments of different prices and durations. Also called PV01 or BPV (basis-point value).',
  },
  {
    cat: 'FIXED INCOME',
    term: 'Yield Curve',
    notation: 'y(τ) = par yield at tenor τ',
    def: 'The relationship between yield and maturity for a set of homogeneous bonds (usually Treasuries). Can be represented as spot curve, par curve, or forward curve. Shape encodes growth and inflation expectations plus the term premium. Inversion (short > long) has historically preceded recessions by 6-18 months with high but imperfect accuracy.',
  },
  {
    cat: 'FIXED INCOME',
    term: 'Term Premium',
    notation: 'TP = y_long - E[avg short-rate]',
    def: "The excess yield long-dated bonds earn over the expected average of short rates. Compensates investors for bearing duration risk — uncertainty about future rates and inflation. Estimated via affine term-structure models (Kim-Wright, Adrian-Crump-Moench). Can go negative in 'flight-to-safety' regimes.",
  },
  {
    cat: 'FIXED INCOME',
    term: 'OAS (Option-Adjusted Spread)',
    notation: 'OAS = spread over Treasuries after stripping embedded options',
    def: "For bonds with embedded options (callable corporates, MBS), OAS is the spread over the Treasury curve after computing the option's value via a term-structure model. Strips out the optionality to give a fair comparison to option-free bonds. The industry-standard relative-value metric in credit and MBS.",
  },
  {
    cat: 'FIXED INCOME',
    term: 'Z-Spread',
    notation: 'PV(CFs) = Σ CF_i · exp(-(z_i + Z) · t_i)',
    def: "The constant spread added to the zero-coupon Treasury curve that makes the PV of a bond's cash flows equal its market price. Unlike yield spread, it respects the full term structure — crucial for non-par, long-dated, or front-loaded bonds. For option-free bonds with stable cash flows, Z-spread ≈ OAS.",
  },
];

const CATEGORIES = [
  'ALL',
  'STOCHASTIC CALCULUS',
  'DERIVATIVES',
  'PORTFOLIO THEORY',
  'MARKET MICROSTRUCTURE',
  'FIXED INCOME',
];

export default function GlossaryPage() {
  const [query, setQuery] = useState('');
  const [activeCat, setActiveCat] = useState('ALL');

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return GLOSSARY.filter((e) => {
      if (activeCat !== 'ALL' && e.cat !== activeCat) return false;
      if (!q) return true;
      return (
        e.term.toLowerCase().includes(q) ||
        e.def.toLowerCase().includes(q) ||
        e.cat.toLowerCase().includes(q)
      );
    });
  }, [query, activeCat]);

  const grouped = useMemo(() => {
    const out = {};
    filtered.forEach((e) => {
      if (!out[e.cat]) out[e.cat] = [];
      out[e.cat].push(e);
    });
    return out;
  }, [filtered]);

  return (
    <>
      <Helmet>
        <title>DDF·TERMINAL — Glossary</title>
        <meta name="description" content="Quant finance glossary — stochastic calculus, derivatives, portfolio theory, microstructure, fixed income terms with definitions and notation." />
        <link rel="canonical" href="https://findmitridefreitas.com/glossary" />
      </Helmet>

      <div className="min-h-screen pt-12 md:pt-14 pb-20">
        <section className="py-8 border-b border-border">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-5xl">
            <Link to="/" className="font-mono text-[10px] tracking-widest text-muted-foreground hover:text-primary transition-colors inline-flex items-center gap-1 mb-5">
              <ArrowLeft className="h-3 w-3" /> BACK
            </Link>
            <div className="flex items-center gap-2 mb-2">
              <BookOpen className="h-4 w-4 text-primary" />
              <span className="font-mono text-[10px] tracking-widest text-primary">REFERENCE</span>
            </div>
            <h1 className="font-mono text-2xl md:text-4xl font-bold tracking-tight text-foreground leading-tight mb-2">
              Glossary
            </h1>
            <p className="font-mono text-[11px] text-muted-foreground">
              {GLOSSARY.length} quant finance terms · {CATEGORIES.length - 1} categories
            </p>
          </div>
        </section>

        {/* Search + filter */}
        <section className="py-6 border-b border-border sticky top-10 md:top-11 bg-background/95 backdrop-blur z-30">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-5xl space-y-3">
            <div className="flex items-center gap-2 border border-border bg-muted/10 px-3 py-2">
              <Search className="h-3.5 w-3.5 text-muted-foreground/60" />
              <input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search terms or definitions..."
                className="flex-1 bg-transparent font-mono text-xs text-foreground placeholder:text-muted-foreground/30 focus:outline-none"
              />
              {query && (
                <button onClick={() => setQuery('')} className="font-mono text-[9px] tracking-widest text-muted-foreground/50 hover:text-primary">
                  CLEAR
                </button>
              )}
              <span className="font-mono text-[9px] tracking-widest text-muted-foreground/40">
                {filtered.length} / {GLOSSARY.length}
              </span>
            </div>

            <div className="flex flex-wrap gap-1.5">
              {CATEGORIES.map((c) => (
                <button
                  key={c}
                  onClick={() => setActiveCat(c)}
                  className={`font-mono text-[9px] tracking-widest px-2 py-1 border transition-colors ${
                    activeCat === c
                      ? 'bg-primary text-primary-foreground border-primary'
                      : 'border-border text-muted-foreground hover:border-primary hover:text-primary'
                  }`}
                >
                  {c}
                </button>
              ))}
            </div>
          </div>
        </section>

        {/* Results */}
        <section className="py-8">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-5xl">
            {filtered.length === 0 ? (
              <p className="font-mono text-[11px] text-muted-foreground/50 text-center py-12 tracking-widest">
                NO MATCHES FOR &quot;{query}&quot;
              </p>
            ) : (
              Object.entries(grouped).map(([cat, items]) => (
                <div key={cat} className="mb-10">
                  <div className="flex items-center gap-3 mb-4 border-b border-border pb-2">
                    <span className="font-mono text-[10px] tracking-widest text-primary">{cat}</span>
                    <span className="font-mono text-[9px] tracking-widest text-muted-foreground/40">
                      {items.length} TERM{items.length !== 1 ? 'S' : ''}
                    </span>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {items.map((e) => (
                      <div
                        key={e.term}
                        className="border border-border bg-background hover:border-primary/50 transition-colors p-4"
                      >
                        <h3 className="font-mono text-[13px] font-bold text-foreground mb-1">
                          {e.term}
                        </h3>
                        {e.notation && (
                          <div className="font-mono text-[10px] text-primary/80 bg-muted/20 border border-border/50 px-2 py-1 mb-2 overflow-x-auto">
                            {e.notation}
                          </div>
                        )}
                        <p className="font-mono text-[11px] text-muted-foreground leading-[1.7]">
                          {e.def}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              ))
            )}
          </div>
        </section>

        <section className="py-6 border-t border-border">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-5xl">
            <p className="font-mono text-[9px] text-muted-foreground/40 tracking-widest text-center">
              FOR LONGER FORM · <Link to="/research" className="hover:text-primary">RESEARCH WRITEUPS</Link> · <Link to="/lab" className="hover:text-primary">LAB TOOLS</Link>
            </p>
          </div>
        </section>
      </div>
    </>
  );
}
